export const googleBooksCategories = [
  "Accounting",
  "Anthropology",
  "Architecture",
  "Art",
  "Biography & Autobiography",
  "Biology",
  "Business & Economics",
  "Chemistry",
  "Communication Studies",
  "Computers",
  "Computers / Artificial Intelligence",
  "Computers / Cybersecurity",
  "Computers / Data Science",
  "Computers / Hardware",
  "Computers / Programming",
  "Computers / Software Development",
  "Cooking",
  "Cultural Studies",
  "Design",
  "Economics",
  "Education",
  "Education / Teaching",
  "Electronics",
  "Embedded Systems",
  "Engineering",
  "Entrepreneurship",
  "Film",
  "Finance",
  "Fiction",
  "Food",
  "Gardening",
  "Geography",
  "Healths",
  "History",
  "Hobbies",
  "Investing",
  "Juvenile Fiction",
  "Juvenile Nonfiction",
  "Language Learning",
  "Law",
  "Leadership",
  "Linguistics",
  "Management",
  "Marketing",
  "Mathematics",
  "Media Studies",
  "Medical",
  "Mental Health",
  "Music",
  "Nonfiction",
  "Nursing",
  "Performing Arts",
  "Personal Development",
  "Philosophy",
  "Photography",
  "Physics",
  "Political Science",
  "Psychology",
  "Public Health",
  "Reference",
  "Religion",
  "Robotics",
  "Science",
  "Self-Help",
  "Sociology",
  "Sports & Recreation",
  "Study Aids",
  "Technology",
  "Travel"
];
